debug: false


support-radius: 5
top-support-radius: 2

fall-delay-minutes: 0.1

# Instability particle colors (order: start, middle, end)
instability-colors:
  - yellow
  - orange
  - red

allow-placing-unstable-blocks: true

# Behavior of falling blocks (FallingBlock) created by the plugin
falling-block: true
falling-block-drop-item: true
falling-block-hurt-entities: true


no-rest-blocks-vertical:
  - lava
  - water
  - fire
  - powder_snow
  - scaffolding

no-rest-blocks-horizontal:
  - lava
  - water
  - fire
  - powder_snow
  - scaffolding
  # Blocks that fall by default in Minecraft (always stable for the plugin)
  - sand
  - suspicious_sand
  - red_sand
  - gravel
  - white_concrete_powder
  - orange_concrete_powder
  - magenta_concrete_powder
  - light_blue_concrete_powder
  - yellow_concrete_powder
  - lime_concrete_powder
  - pink_concrete_powder
  - gray_concrete_powder
  - light_gray_concrete_powder
  - cyan_concrete_powder
  - purple_concrete_powder
  - blue_concrete_powder
  - brown_concrete_powder
  - green_concrete_powder
  - red_concrete_powder
  - black_concrete_powder

always-stable-blocks:
  - air
  - bedrock
  - water
  - lava
  - acacia_leaves
  - birch_leaves
  - dark_oak_leaves
  - jungle_leaves
  - oak_leaves
  - spruce_leaves
  - mangrove_leaves
  - cherry_leaves
  # Blocks that fall by default in Minecraft (always stable for the plugin)
  - sand
  - suspicious_sand
  - red_sand
  - gravel
  - white_concrete_powder
  - orange_concrete_powder
  - magenta_concrete_powder
  - light_blue_concrete_powder
  - yellow_concrete_powder
  - lime_concrete_powder
  - pink_concrete_powder
  - gray_concrete_powder
  - light_gray_concrete_powder
  - cyan_concrete_powder
  - purple_concrete_powder
  - blue_concrete_powder
  - brown_concrete_powder
  - green_concrete_powder
  - red_concrete_powder
  - black_concrete_powder



# Blocks considered as "floating":
# they can rest on water as if it was solid support.
floating-support-blocks:
  - lily_pad
  - seagrass
  - tall_seagrass
  - birch_leaves
  - dark_oak_leaves
  - jungle_leaves
  - oak_leaves
  - spruce_leaves
  - mangrove_leaves
  - cherry_leaves
  - acacia_log
  - birch_log
  - dark_oak_log
  - jungle_log
  - oak_log
  - spruce_log
  - mangrove_log
  - cherry_log


